[target.thumbv7m-none-eabi]
runner = 'probe-run --chip stm32f103VF'  # Economizer // Z-Axis // bltouch
rustflags = [
   "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7m-none-eabi"

# [env]
# DEFMT_LOG = "info"